/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvatarsIndexRouteImport } from './routes/avatars.index'
import { Route as StylistAvatarIdRouteImport } from './routes/stylist.$avatarId'
import { Route as StudioAvatarIdRouteImport } from './routes/studio.$avatarId'
import { Route as AvatarsNewRouteImport } from './routes/avatars.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarsIndexRoute = AvatarsIndexRouteImport.update({
  id: '/avatars/',
  path: '/avatars/',
  getParentRoute: () => rootRouteImport,
} as any)
const StylistAvatarIdRoute = StylistAvatarIdRouteImport.update({
  id: '/stylist/$avatarId',
  path: '/stylist/$avatarId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAvatarIdRoute = StudioAvatarIdRouteImport.update({
  id: '/studio/$avatarId',
  path: '/studio/$avatarId',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarsNewRoute = AvatarsNewRouteImport.update({
  id: '/avatars/new',
  path: '/avatars/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/avatars/new': typeof AvatarsNewRoute
  '/studio/$avatarId': typeof StudioAvatarIdRoute
  '/stylist/$avatarId': typeof StylistAvatarIdRoute
  '/avatars/': typeof AvatarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/avatars/new': typeof AvatarsNewRoute
  '/studio/$avatarId': typeof StudioAvatarIdRoute
  '/stylist/$avatarId': typeof StylistAvatarIdRoute
  '/avatars': typeof AvatarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/avatars/new': typeof AvatarsNewRoute
  '/studio/$avatarId': typeof StudioAvatarIdRoute
  '/stylist/$avatarId': typeof StylistAvatarIdRoute
  '/avatars/': typeof AvatarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/saved'
    | '/settings'
    | '/avatars/new'
    | '/studio/$avatarId'
    | '/stylist/$avatarId'
    | '/avatars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/saved'
    | '/settings'
    | '/avatars/new'
    | '/studio/$avatarId'
    | '/stylist/$avatarId'
    | '/avatars'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/saved'
    | '/settings'
    | '/avatars/new'
    | '/studio/$avatarId'
    | '/stylist/$avatarId'
    | '/avatars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  AvatarsNewRoute: typeof AvatarsNewRoute
  StudioAvatarIdRoute: typeof StudioAvatarIdRoute
  StylistAvatarIdRoute: typeof StylistAvatarIdRoute
  AvatarsIndexRoute: typeof AvatarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatars/': {
      id: '/avatars/'
      path: '/avatars'
      fullPath: '/avatars/'
      preLoaderRoute: typeof AvatarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stylist/$avatarId': {
      id: '/stylist/$avatarId'
      path: '/stylist/$avatarId'
      fullPath: '/stylist/$avatarId'
      preLoaderRoute: typeof StylistAvatarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$avatarId': {
      id: '/studio/$avatarId'
      path: '/studio/$avatarId'
      fullPath: '/studio/$avatarId'
      preLoaderRoute: typeof StudioAvatarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatars/new': {
      id: '/avatars/new'
      path: '/avatars/new'
      fullPath: '/avatars/new'
      preLoaderRoute: typeof AvatarsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  AvatarsNewRoute: AvatarsNewRoute,
  StudioAvatarIdRoute: StudioAvatarIdRoute,
  StylistAvatarIdRoute: StylistAvatarIdRoute,
  AvatarsIndexRoute: AvatarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
